### PR TITLE
Removes deprecated interpolation-only expressions

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
results of `make test`:
```
PASS
ok      tardigarde-ci/tests     500.298s
[terratest/test]: Completed successfully!
```

**Review by kbalk — COMMENTED** [review]
There are a lot of superfluous quotes, which is something you corrected in the terraform-null-validate-list-item pull request.  Were you planning on a second pull request for those changes?

**Comment by lorengordon** [comment]
@kbalk I think I was minimizing the changes in this pr, as this module is on the list to remove the create/enable var. Was saving the cleanup for that task...

**Review by kbalk — APPROVED** [review]
Looks good for the interpolation-only expressions.

**Pull request merged**
